services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - BASE_URL=http://localhost:8000
      - PORT=8000
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:135710@db:5432/mtn
      - JWT_SECRET_KEY=123MNQQ4234mflozzziu
      - JWT_REFRESH_SECRET_KEY=123MFQQ@42649Flozzziu
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 135710
      POSTGRES_DB: mtn
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
